// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZaB1ioAkWD2X58Q8rom9PdHOZrLsCY9g',
    appId: '1:19972814983:web:04392765e5fbf6e809a022',
    messagingSenderId: '19972814983',
    projectId: 'n1ygrghaejvpa30gz59v0cdr27e5le',
    authDomain: 'n1ygrghaejvpa30gz59v0cdr27e5le.firebaseapp.com',
    storageBucket: 'n1ygrghaejvpa30gz59v0cdr27e5le.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB46CJaHVw-rZcnIxfol6G8rAq76-UgKbI',
    appId: '1:19972814983:android:83fb561521efa39109a022',
    messagingSenderId: '19972814983',
    projectId: 'n1ygrghaejvpa30gz59v0cdr27e5le',
    storageBucket: 'n1ygrghaejvpa30gz59v0cdr27e5le.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9gnX5ipJQtFMTHMWPJUYpKEYct0YopXA',
    appId: '1:19972814983:ios:c4ffc5f1a04cb7b209a022',
    messagingSenderId: '19972814983',
    projectId: 'n1ygrghaejvpa30gz59v0cdr27e5le',
    storageBucket: 'n1ygrghaejvpa30gz59v0cdr27e5le.firebasestorage.app',
    iosBundleId: 'roadygo.stackone.main',
  );
}
